version: '3'

services:
  php:
    build: .
    restart: always
    container_name: exerciseArea
    ports:
      - "8081:80"
    volumes:
      - ./app/public:/var/www/html/
      - ./app/src:/var/www/src
      - ./app/tests:/var/www/

  
   
