version: '3'

services:
  web:
    build: .
    restart: unless-stopped
    container_name: php_web
    volumes:
      - ./view/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true

  composer:
    image: composer:2
    command: ["composer", "install"]
    volumes:
      - ./view/:/app
