# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: php:8.0.12-apache
    steps:
      - run: apt update && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
          apt -y install zip  && php composer-setup.php --install-dir=/usr/local/bin --filename=composer 
      - run: cd /var/www/html 
      - run: composer install 
      - run: ./vendor/bin/phpunit ./tests 
