version: 2.1
workflows:
  testmyapp:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: php:8.0.12-apache
    working_directory: ~/temp
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c2:3f:9d:a0:32:cd:1a:61:af:18:d2:69:ef:bc:cd:ad"
      - checkout
      - run: apt update
      - run: ls
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" 
      - run: apt -y install zip
      - run: php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - run: composer require  phpunit/phpunit ^9.5
      - run: composer install --prefer-source --no-interaction --no-dev
      - run: ./vendor/bin/phpunit ./app/tests
