version: 2.1
workflows:
  testmyapp:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: php:8.0.12-apache
    working_directory: ~/temp
    steps: 
      - checkout
      - run: apt update
      - run: ls
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" 
      - run: apt -y install zip
      - run: php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - run: composer require  phpunit/phpunit ^9.5
      - rum: composer install --prefer-source --no-interaction --no-dev
      - run: ./vendor/bin/phpunit ./app/tests
