version: 2.1
workflows:
  testmyapp:
    jobs:
      - test
jobs:
  test:
    working_directory: ~/temp
    docker:
      - image: php:8.0.12-apache
    steps:
      - run: apt update
      - run: ls
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" 
      - run: apt -y install zip
      - run: php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - run: composer require --dev phpunit/phpunit ^9.5
    steps:
      - checkout  
      - run: ls
      - run: ./vendor/bin/phpunit ./tests
